# Generated by Django 5.0.6 on 2025-05-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LockBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=8, unique=True, verbose_name='ID устройства')),
                ('device_type', models.CharField(default='0025', max_length=4, verbose_name='Тип устройства')),
                ('ccid', models.CharField(blank=True, max_length=20, verbose_name='CCID SIM карты')),
                ('board_address', models.IntegerField(default=0, verbose_name='Адрес платы')),
                ('total_channels', models.IntegerField(default=25, verbose_name='Количество каналов')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Последний heartbeat')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Плата управления замками',
                'verbose_name_plural': 'Платы управления замками',
            },
        ),
        migrations.CreateModel(
            name='LockOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('open_single', 'Открытие одного замка'), ('open_all', 'Открытие всех замков'), ('open_multiple', 'Открытие нескольких замков'), ('read_status', 'Чтение статуса'), ('read_all_status', 'Чтение всех статусов'), ('keep_open', 'Постоянное открытие'), ('close_channel', 'Закрытие канала')], max_length=20)),
                ('channels', models.JSONField(default=list, verbose_name='Каналы')),
                ('order_number', models.CharField(blank=True, max_length=24, verbose_name='Номер заказа')),
                ('success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.lockboard')),
            ],
            options={
                'verbose_name': 'Операция с замком',
                'verbose_name_plural': 'Операции с замками',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField(verbose_name='Номер канала')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(0, 'Открыт'), (1, 'Закрыт')], default=1, verbose_name='Статус')),
                ('last_status_change', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение статуса')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='locks.lockboard')),
            ],
            options={
                'verbose_name': 'Замок',
                'verbose_name_plural': 'Замки',
                'unique_together': {('board', 'channel')},
            },
        ),
    ]
